In [3]:
import numpy as np
import pandas as pd
import os
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive/Kaggle/Old_Titanic/Titanic

Mounted at /content/drive
/content/drive/MyDrive/Kaggle/Old_Titanic/Titanic


In [79]:
df = pd.read_csv('train.csv')
dftest = df[['Fare','SibSp']]
testarr = dftest.to_numpy()
X=testarr[0:5,:].T
Y = df['Survived'].to_numpy()
Y = Y[0:5]
X.shape
X

array([[ 7.25  , 71.2833,  7.925 , 53.1   ,  8.05  ],
       [ 1.    ,  1.    ,  0.    ,  1.    ,  0.    ]])

Start with logistic regression and gradient descent based on the first section of the deep learning and 




In [178]:
class log_reg:
    def __init__(self):
        self.W=[] # Weights
        self.b=[] # Biases
        self.z=np.array([0, 2]) # Linear term)
        self.dz=0 # Derivative of loss w.r.t. Z
        self.dW=0 
        self.db =0 
        self.loss=0
        self.A =0
        self.Y_predict =0
        self.score=0

    def initialize_parm(self,X):

        self.W = np.random.rand(X.shape[0],1) # Number of features
        
        self.b = 0
    
    def sigmoid(self):
        A=1 / (1 + np.exp(-self.z))
        return A

    def forward_prop(self,X,Y):
        m = X.shape[1]
        self.z = np.dot(self.W.T,X) + self.b # Vectorized implementation

        self.A = self.sigmoid()
        
        self.loss = -(1/m)*np.sum(Y*np.log(self.A)+(1-Y)*np.log(1-self.A)) # Cost function for logistic regressopn
    
    def backward_prop(self,X,Y):
        m = X.shape[1]
        dz = self.A - Y # Derivative of cost function w.r.t. dz 
        #print(dz)
        '''
        dA = -Y/A + (1-y)/(1-a) applying chain rule leads to dZ = A-Y
        '''
        self.dW = (1/m)*np.dot(X,(self.A-Y).T)

        self.db = (1/m)*np.sum(self.A-Y)


    def update_parm(self,learning_rate):
        self.W = self.W - learning_rate * self.dW
        self.b = self.b - learning_rate * self.db

    def train(self,X,Y,num_it=10000,learning_rate=0.01):
        # X should be in shape (n_x,m)

        self.initialize_parm(X)
        for ii in range(num_it):
            self.forward_prop(X,Y)
            #print('Loss after ' +str(ii) + 'th iteration: ' + str(self.loss))
            self.backward_prop(X,Y)
            self.update_parm(learning_rate)
            

    def predict(self,X):
        self.z = np.dot(self.W.T,X) + self.b # Vectorized implementation
        A_temp = self.sigmoid()
        self.Y_predict = np.where(A_temp <= 0.5,0,1)
        return self.Y_predict
  

In [75]:
logreg_model = log_reg()
logreg_model.train(X,Y)

[[0.90539949 0.99999994 0.85570952 0.99999648 0.85914174]]
Loss after 0th iteration: -0.8947842919947999
[[0.61106868 0.27605499 0.45630183 0.36307529 0.45561618]]
Loss after 1th iteration: -0.9274708502408283
[[0.99999547 1.         0.99999714 1.         0.99999766]]
Loss after 2th iteration: nan
[[0.99995749 1.         0.99996766 1.         0.99997253]]
Loss after 3th iteration: nan
[[0.99960144 1.         0.99963462 1.         0.99967749]]
Loss after 4th iteration: nan
[[0.99627879 1.         0.99589117 1.         0.99623074]]
Loss after 5th iteration: nan
[[0.96657926 1.         0.95604737 1.         0.95804394]]
Loss after 6th iteration: -1.322931735198666
[[0.77926165 0.99956502 0.69035766 0.99726839 0.69305451]]
Loss after 7th iteration: -0.6131156425835647
[[0.49975651 0.01061609 0.36329014 0.03742464 0.36124544]]
Loss after 8th iteration: -1.996851852682362
[[0.99999997 1.         0.99999999 1.         0.99999999]]
Loss after 9th iteration: nan


<ipython-input-74-02d81b94aa05>:27: RuntimeWarning: divide by zero encountered in log
  self.loss = (1/m)*np.sum(Y*np.log(self.A)+(1-Y)*np.log(1-self.A)) # Cost function for logistic regressopn
<ipython-input-74-02d81b94aa05>:27: RuntimeWarning: invalid value encountered in multiply
  self.loss = (1/m)*np.sum(Y*np.log(self.A)+(1-Y)*np.log(1-self.A)) # Cost function for logistic regressopn


In [78]:
logreg_model.predict(X)

array([[1, 1, 1, 1, 1]])

In [94]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression().fit(X.T, Y)
clf.predict(X.T)


array([0, 1, 0, 1, 0])

In [168]:
from sklearn.datasets import load_breast_cancer
Xt, yt = load_breast_cancer(return_X_y=True)
clf = LogisticRegression().fit(Xt, yt)
clf.predict(Xt)
clf.score(Xt, yt)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9490333919156415

In [170]:
yT =yt.T.reshape(1,yt.shape[0])
Xt.T.shape

(30, 569)

In [180]:
iris_model = log_reg()
iris_model.train(Xt.T,yT)

<ipython-input-178-82c641617481>:29: RuntimeWarning: divide by zero encountered in log
  self.loss = -(1/m)*np.sum(Y*np.log(self.A)+(1-Y)*np.log(1-self.A)) # Cost function for logistic regressopn
<ipython-input-178-82c641617481>:29: RuntimeWarning: invalid value encountered in multiply
  self.loss = -(1/m)*np.sum(Y*np.log(self.A)+(1-Y)*np.log(1-self.A)) # Cost function for logistic regressopn
<ipython-input-178-82c641617481>:20: RuntimeWarning: overflow encountered in exp
  A=1 / (1 + np.exp(-self.z))


In [181]:
trainpredict=iris_model.predict(Xt.T)

<ipython-input-178-82c641617481>:20: RuntimeWarning: overflow encountered in exp
  A=1 / (1 + np.exp(-self.z))


In [182]:
100 - np.mean(np.abs(trainpredict- yT)) * 100

89.63093145869948